//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class eng_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eng_lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.eng-lang", typeof(eng_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  .
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin Options.
        /// </summary>
        internal static string admin_options {
            get {
                return ResourceManager.GetString("admin options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string btnaceptar {
            get {
                return ResourceManager.GetString("btnaceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply Family.
        /// </summary>
        internal static string btnaplicarfamilia {
            get {
                return ResourceManager.GetString("btnaplicarfamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign.
        /// </summary>
        internal static string btnasignar {
            get {
                return ResourceManager.GetString("btnasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Config User Profile.
        /// </summary>
        internal static string btnasignarpermisos {
            get {
                return ResourceManager.GetString("btnasignarpermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign User Operatios.
        /// </summary>
        internal static string btnasignarpermisosusuario {
            get {
                return ResourceManager.GetString("btnasignarpermisosusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string btnback {
            get {
                return ResourceManager.GetString("btnback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BackUp.
        /// </summary>
        internal static string btnbackup {
            get {
                return ResourceManager.GetString("btnbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log.
        /// </summary>
        internal static string btnbitacora {
            get {
                return ResourceManager.GetString("btnbitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Log.
        /// </summary>
        internal static string btnconsultarbitacora {
            get {
                return ResourceManager.GetString("btnconsultarbitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string btncreate {
            get {
                return ResourceManager.GetString("btncreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create User.
        /// </summary>
        internal static string btncreateuser {
            get {
                return ResourceManager.GetString("btncreateuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string btndelete {
            get {
                return ResourceManager.GetString("btndelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Family.
        /// </summary>
        internal static string btndeletefamily {
            get {
                return ResourceManager.GetString("btndeletefamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete User.
        /// </summary>
        internal static string btndeleteuser {
            get {
                return ResourceManager.GetString("btndeleteuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unassign .
        /// </summary>
        internal static string btndesasignar {
            get {
                return ResourceManager.GetString("btndesasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Digits.
        /// </summary>
        internal static string btndigitosverificadores {
            get {
                return ResourceManager.GetString("btndigitosverificadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export Log.
        /// </summary>
        internal static string btnexportlog {
            get {
                return ResourceManager.GetString("btnexportlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string btnlogin {
            get {
                return ResourceManager.GetString("btnlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string btnModal {
            get {
                return ResourceManager.GetString("btnModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Users.
        /// </summary>
        internal static string btnpermisos {
            get {
                return ResourceManager.GetString("btnpermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read.
        /// </summary>
        internal static string btnread {
            get {
                return ResourceManager.GetString("btnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read User.
        /// </summary>
        internal static string btnreaduser {
            get {
                return ResourceManager.GetString("btnreaduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recheck Digits.
        /// </summary>
        internal static string btnrecalculardigitos {
            get {
                return ResourceManager.GetString("btnrecalculardigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore.
        /// </summary>
        internal static string btnrestore {
            get {
                return ResourceManager.GetString("btnrestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string btnupdate {
            get {
                return ResourceManager.GetString("btnupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Family.
        /// </summary>
        internal static string btnupdatefamily {
            get {
                return ResourceManager.GetString("btnupdatefamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update User.
        /// </summary>
        internal static string btnupdateuser {
            get {
                return ResourceManager.GetString("btnupdateuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users Operations.
        /// </summary>
        internal static string btnusuarios {
            get {
                return ResourceManager.GetString("btnusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string btnvolver {
            get {
                return ResourceManager.GetString("btnvolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        internal static string chkhabilitado {
            get {
                return ResourceManager.GetString("chkhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password does not meet the requirements: &lt;br&gt; -It must have between 8 and 15 characters &lt;br&gt; -It must have at least one uppercase and one lowercase letter &lt;br&gt; -It must have at least one number..
        /// </summary>
        internal static string errRegexPassword {
            get {
                return ResourceManager.GetString("errRegexPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string fechaevento {
            get {
                return ResourceManager.GetString("fechaevento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name :.
        /// </summary>
        internal static string lblapellido {
            get {
                return ResourceManager.GetString("lblapellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make Back Up.
        /// </summary>
        internal static string lblbackuptittle {
            get {
                return ResourceManager.GetString("lblbackuptittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logs.
        /// </summary>
        internal static string lblbitacoratitulo {
            get {
                return ResourceManager.GetString("lblbitacoratitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key.
        /// </summary>
        internal static string lblclave {
            get {
                return ResourceManager.GetString("lblclave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string lblclaveusuario {
            get {
                return ResourceManager.GetString("lblclaveusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticality.
        /// </summary>
        internal static string lblcriticidad {
            get {
                return ResourceManager.GetString("lblcriticidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Name.
        /// </summary>
        internal static string lbldescfamilia {
            get {
                return ResourceManager.GetString("lbldescfamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        internal static string lbldesde {
            get {
                return ResourceManager.GetString("lbldesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family Module.
        /// </summary>
        internal static string lblgestorfamilias {
            get {
                return ResourceManager.GetString("lblgestorfamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Module.
        /// </summary>
        internal static string lblgestorusuarios {
            get {
                return ResourceManager.GetString("lblgestorusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        internal static string lblhabilitado {
            get {
                return ResourceManager.GetString("lblhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To.
        /// </summary>
        internal static string lblhasta {
            get {
                return ResourceManager.GetString("lblhasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string lbllogin {
            get {
                return ResourceManager.GetString("lbllogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string lblmail {
            get {
                return ResourceManager.GetString("lblmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string lblnombre {
            get {
                return ResourceManager.GetString("lblnombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assigned Permissions.
        /// </summary>
        internal static string lblpermisosasignados {
            get {
                return ResourceManager.GetString("lblpermisosasignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unassigned Permissions.
        /// </summary>
        internal static string lblpermisosnoasignados {
            get {
                return ResourceManager.GetString("lblpermisosnoasignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Path.
        /// </summary>
        internal static string lblrutabackup {
            get {
                return ResourceManager.GetString("lblrutabackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Path.
        /// </summary>
        internal static string lblrutarestore {
            get {
                return ResourceManager.GetString("lblrutarestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Rol.
        /// </summary>
        internal static string lblseleccionarfamilia {
            get {
                return ResourceManager.GetString("lblseleccionarfamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select User.
        /// </summary>
        internal static string lblseleccionarusuario {
            get {
                return ResourceManager.GetString("lblseleccionarusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Re-check Digits.
        /// </summary>
        internal static string lbltitulorecalculardigitos {
            get {
                return ResourceManager.GetString("lbltitulorecalculardigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string lblusuario {
            get {
                return ResourceManager.GetString("lblusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For change password, please click here .
        /// </summary>
        internal static string LinkButton1 {
            get {
                return ResourceManager.GetString("LinkButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        internal static string mensaje {
            get {
                return ResourceManager.GetString("mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MensajeCuerpo.
        /// </summary>
        internal static string MensajeCuerpo {
            get {
                return ResourceManager.GetString("MensajeCuerpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MensajeHeader.
        /// </summary>
        internal static string MensajeHeader {
            get {
                return ResourceManager.GetString("MensajeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin Options.
        /// </summary>
        internal static string Opciones_del_Administrador {
            get {
                return ResourceManager.GetString("Opciones del Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of Event.
        /// </summary>
        internal static string TipoEventoSt {
            get {
                return ResourceManager.GetString("TipoEventoSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description Profile.
        /// </summary>
        internal static string txtdescperfil {
            get {
                return ResourceManager.GetString("txtdescperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        internal static string txtemail {
            get {
                return ResourceManager.GetString("txtemail", resourceCulture);
            }
        }
    }
}
