//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class esp_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal esp_lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.esp-lang", typeof(esp_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  .
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones del Administrador.
        /// </summary>
        internal static string Admin_Options {
            get {
                return ResourceManager.GetString("Admin Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnaceptar {
            get {
                return ResourceManager.GetString("btnaceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Familia.
        /// </summary>
        internal static string btnaplicarfamilia {
            get {
                return ResourceManager.GetString("btnaplicarfamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar .
        /// </summary>
        internal static string btnasignar {
            get {
                return ResourceManager.GetString("btnasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Permisos a Familia.
        /// </summary>
        internal static string btnasignarpermisos {
            get {
                return ResourceManager.GetString("btnasignarpermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Permisos a Usuario.
        /// </summary>
        internal static string btnasignarpermisosusuario {
            get {
                return ResourceManager.GetString("btnasignarpermisosusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string btnback {
            get {
                return ResourceManager.GetString("btnback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back Up.
        /// </summary>
        internal static string btnbackup {
            get {
                return ResourceManager.GetString("btnbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitácora.
        /// </summary>
        internal static string btnbitacora {
            get {
                return ResourceManager.GetString("btnbitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Bitácora.
        /// </summary>
        internal static string btnconsultarbitacora {
            get {
                return ResourceManager.GetString("btnconsultarbitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string btncreate {
            get {
                return ResourceManager.GetString("btncreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Usuario.
        /// </summary>
        internal static string btncreateuser {
            get {
                return ResourceManager.GetString("btncreateuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string btndelete {
            get {
                return ResourceManager.GetString("btndelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Familia.
        /// </summary>
        internal static string btndeletefamily {
            get {
                return ResourceManager.GetString("btndeletefamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string btndeleteuser {
            get {
                return ResourceManager.GetString("btndeleteuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desasignar.
        /// </summary>
        internal static string btndesasignar {
            get {
                return ResourceManager.GetString("btndesasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dígitos Verificadores.
        /// </summary>
        internal static string btndigitosverificadores {
            get {
                return ResourceManager.GetString("btndigitosverificadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Bitácora.
        /// </summary>
        internal static string btnexportlog {
            get {
                return ResourceManager.GetString("btnexportlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string btnlogin {
            get {
                return ResourceManager.GetString("btnlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnModal {
            get {
                return ResourceManager.GetString("btnModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string btnpermisos {
            get {
                return ResourceManager.GetString("btnpermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer.
        /// </summary>
        internal static string btnread {
            get {
                return ResourceManager.GetString("btnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer Usuario.
        /// </summary>
        internal static string btnreaduser {
            get {
                return ResourceManager.GetString("btnreaduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore.
        /// </summary>
        internal static string btnrestore {
            get {
                return ResourceManager.GetString("btnrestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string btnupdate {
            get {
                return ResourceManager.GetString("btnupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Familia.
        /// </summary>
        internal static string btnupdatefamily {
            get {
                return ResourceManager.GetString("btnupdatefamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Usuario.
        /// </summary>
        internal static string btnupdateuser {
            get {
                return ResourceManager.GetString("btnupdateuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string btnusuarios {
            get {
                return ResourceManager.GetString("btnusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string btnvolver {
            get {
                return ResourceManager.GetString("btnvolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string chkhabilitado {
            get {
                return ResourceManager.GetString("chkhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El password requiere minimo 8 caracteres, una letra mayuscula y numeros.
        /// </summary>
        internal static string errRegexPassword {
            get {
                return ResourceManager.GetString("errRegexPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string fechaevento {
            get {
                return ResourceManager.GetString("fechaevento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string lblapellido {
            get {
                return ResourceManager.GetString("lblapellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitácora.
        /// </summary>
        internal static string lblbitacoratitulo {
            get {
                return ResourceManager.GetString("lblbitacoratitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string lblclave {
            get {
                return ResourceManager.GetString("lblclave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string lblclaveusuario {
            get {
                return ResourceManager.GetString("lblclaveusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticidad.
        /// </summary>
        internal static string lblcriticidad {
            get {
                return ResourceManager.GetString("lblcriticidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título Perfil.
        /// </summary>
        internal static string lbldescfamilia {
            get {
                return ResourceManager.GetString("lbldescfamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string lbldesde {
            get {
                return ResourceManager.GetString("lbldesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestor de Familias.
        /// </summary>
        internal static string lblgestorfamilias {
            get {
                return ResourceManager.GetString("lblgestorfamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestor de Usuarios.
        /// </summary>
        internal static string lblgestorUsuarios {
            get {
                return ResourceManager.GetString("lblgestorUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string lblhabilitado {
            get {
                return ResourceManager.GetString("lblhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string lblhasta {
            get {
                return ResourceManager.GetString("lblhasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string lbllogin {
            get {
                return ResourceManager.GetString("lbllogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string lblmail {
            get {
                return ResourceManager.GetString("lblmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblnombre {
            get {
                return ResourceManager.GetString("lblnombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos asignador.
        /// </summary>
        internal static string lblpermisosasignados {
            get {
                return ResourceManager.GetString("lblpermisosasignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos no asignador.
        /// </summary>
        internal static string lblpermisosnoasignados {
            get {
                return ResourceManager.GetString("lblpermisosnoasignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta por defecto.
        /// </summary>
        internal static string lblrutabackup {
            get {
                return ResourceManager.GetString("lblrutabackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta por defecto.
        /// </summary>
        internal static string lblrutarestore {
            get {
                return ResourceManager.GetString("lblrutarestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Usuario.
        /// </summary>
        internal static string lblseleccionarusuario {
            get {
                return ResourceManager.GetString("lblseleccionarusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lbltitulousuario {
            get {
                return ResourceManager.GetString("lbltitulousuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblusuario {
            get {
                return ResourceManager.GetString("lblusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        internal static string mensaje {
            get {
                return ResourceManager.GetString("mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MensajeCuerpo.
        /// </summary>
        internal static string MensajeCuerpo {
            get {
                return ResourceManager.GetString("MensajeCuerpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MensajeHeader.
        /// </summary>
        internal static string MensajeHeader {
            get {
                return ResourceManager.GetString("MensajeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones del Administrador.
        /// </summary>
        internal static string Opciones_del_Administrador {
            get {
                return ResourceManager.GetString("Opciones del Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of Event.
        /// </summary>
        internal static string TipoEventoSt {
            get {
                return ResourceManager.GetString("TipoEventoSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Perfil.
        /// </summary>
        internal static string txtdescperfil {
            get {
                return ResourceManager.GetString("txtdescperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-Mail.
        /// </summary>
        internal static string txtemail {
            get {
                return ResourceManager.GetString("txtemail", resourceCulture);
            }
        }
    }
}
